from abc import ABC,abstractmethod
class CredentialProvider(ABC):
    @abstractmethod
    def store(self,*a,**k):...
    @abstractmethod
    def retrieve_for_authorized_use(self,*a,**k):...
    @abstractmethod
    def rotate(self,*a,**k):...
    @abstractmethod
    def delete(self,*a,**k):...
    @abstractmethod
    def redact(self,*a,**k):...
