RISK={
"READ_PUBLIC":"GREEN","LIST_DIRECTORY":"GREEN","SCREENSHOT":"GREEN","READ_METADATA":"GREEN",
"CREATE_FOLDER":"YELLOW","MOVE_FILE":"YELLOW","COPY_FILE":"YELLOW","DOWNLOAD":"YELLOW","UPLOAD":"YELLOW",
"DELETE":"RED","PUBLISH":"RED","SEND_MESSAGE":"RED","ACCOUNT_CHANGE":"RED","PAYMENT":"RED","FINANCIAL_ACTION":"RED","SECURITY_SETTING_CHANGE":"RED"}
