from abc import ABC, abstractmethod

class BrowserAdapter(ABC):
    @abstractmethod
    def create_context(self, session_id): ...
    @abstractmethod
    def close_context(self, session_id): ...
    @abstractmethod
    def navigate(self, session_id, url, timeout_ms): ...
    @abstractmethod
    def get_page_state(self, session_id): ...
    @abstractmethod
    def find_target(self, session_id, target): ...
    @abstractmethod
    def click(self, session_id, target): ...
    @abstractmethod
    def type(self, session_id, target, value): ...
    @abstractmethod
    def select(self, session_id, target, value): ...
    @abstractmethod
    def scroll(self, session_id, amount): ...
    @abstractmethod
    def keyboard(self, session_id, key): ...
    @abstractmethod
    def upload_file(self, session_id, target, file_ref): ...
    @abstractmethod
    def download_file(self, session_id, target): ...
    @abstractmethod
    def switch_tab(self, session_id, tab_id): ...
    @abstractmethod
    def switch_frame(self, session_id, frame_id): ...
    @abstractmethod
    def screenshot(self, session_id): ...
    @abstractmethod
    def health_check(self, session_id): ...
