"""6.31 ERROR CODES and 6.33 EVENTS — single source of truth.

Every other module raises RuntimeError(E.SOMETHING) using these constants so
the whole agent only ever produces codes that are actually in the spec.
"""


class E:
    DESKTOP_SESSION_FAILED = "DESKTOP_SESSION_FAILED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    DESTINATION_EXISTS = "DESTINATION_EXISTS"
    SOURCE_CHANGED = "SOURCE_CHANGED"
    FILE_LOCKED = "FILE_LOCKED"
    COPY_FAILED = "COPY_FAILED"
    MOVE_FAILED = "MOVE_FAILED"
    RENAME_FAILED = "RENAME_FAILED"
    DELETE_BLOCKED = "DELETE_BLOCKED"
    APPLICATION_NOT_FOUND = "APPLICATION_NOT_FOUND"
    WINDOW_NOT_FOUND = "WINDOW_NOT_FOUND"
    INPUT_TARGET_UNCERTAIN = "INPUT_TARGET_UNCERTAIN"
    SCREEN_OBSERVATION_FAILED = "SCREEN_OBSERVATION_FAILED"
    ACTION_TIMEOUT = "ACTION_TIMEOUT"
    WORKFLOW_REPLAY_UNSAFE = "WORKFLOW_REPLAY_UNSAFE"
    VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED"
    LOOP_DETECTED = "LOOP_DETECTED"


RETRYABLE = {E.FILE_LOCKED, E.ACTION_TIMEOUT, E.DESKTOP_SESSION_FAILED}


class Events:
    DESKTOP_SESSION_CREATED = "DESKTOP_SESSION_CREATED"
    DESKTOP_SESSION_READY = "DESKTOP_SESSION_READY"
    DESKTOP_ACTION_STARTED = "DESKTOP_ACTION_STARTED"
    DESKTOP_ACTION_COMPLETED = "DESKTOP_ACTION_COMPLETED"
    DESKTOP_ACTION_FAILED = "DESKTOP_ACTION_FAILED"
    FILE_SCAN_STARTED = "FILE_SCAN_STARTED"
    FILE_SCAN_COMPLETED = "FILE_SCAN_COMPLETED"
    FILE_CREATED = "FILE_CREATED"
    FILE_COPIED = "FILE_COPIED"
    FILE_MOVED = "FILE_MOVED"
    FILE_RENAMED = "FILE_RENAMED"
    APPLICATION_LAUNCHED = "APPLICATION_LAUNCHED"
    WINDOW_STATE_CHANGED = "WINDOW_STATE_CHANGED"
    DESKTOP_EVIDENCE_CREATED = "DESKTOP_EVIDENCE_CREATED"
    DESKTOP_RECOVERY_STARTED = "DESKTOP_RECOVERY_STARTED"
    DESKTOP_LOOP_DETECTED = "DESKTOP_LOOP_DETECTED"
    DESKTOP_SESSION_FAILED = "DESKTOP_SESSION_FAILED"
