from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any
@dataclass
class Result:
    success:bool; value:Any=None; error:str|None=None
class InstallableComponent(ABC):
    component_id:str
    @abstractmethod
    def resolve(self,context): ...
    @abstractmethod
    def preflight_check(self,context): ...
    @abstractmethod
    def download(self,context): ...
    @abstractmethod
    def verify(self,artifact,context): ...
    @abstractmethod
    def stage(self,artifact,context): ...
    @abstractmethod
    def install(self,staged_artifact,context): ...
    @abstractmethod
    def configure(self,context): ...
    @abstractmethod
    def health_check(self,context): ...
    @abstractmethod
    def activate(self,context): ...
    @abstractmethod
    def rollback(self,context): ...
    @abstractmethod
    def uninstall(self,context): ...
