from abc import ABC, abstractmethod
class RuntimeAdapter(ABC):
    @abstractmethod
    def discover(self): ...
    @abstractmethod
    def install(self,component): ...
    @abstractmethod
    def configure(self,settings): ...
    @abstractmethod
    def start(self): ...
    @abstractmethod
    def stop(self): ...
    @abstractmethod
    def restart(self): ...
    @abstractmethod
    def health_check(self,model=None): ...
    @abstractmethod
    def get_version(self): ...
    @abstractmethod
    def repair(self,component): ...
    @abstractmethod
    def uninstall(self,managed_exclusively=True): ...
