const $=id=>document.getElementById(id);
const STATES={APP_STARTING:'APP_STARTING',SETUP_REQUIRED:'SETUP_REQUIRED',READY:'READY',TASK_CREATING:'TASK_CREATING',TASK_PLANNING:'TASK_PLANNING',WAITING_FOR_USER:'WAITING_FOR_USER',WAITING_FOR_APPROVAL:'WAITING_FOR_APPROVAL',EXECUTING:'EXECUTING',VERIFYING:'VERIFYING',RECOVERING:'RECOVERING',PAUSED:'PAUSED',COMPLETED:'COMPLETED',FAILED:'FAILED',CANCELLED:'CANCELLED'};
const COMMANDS=['TASK_CREATE','TASK_CLARIFY','TASK_APPROVE','TASK_REJECT','TASK_PAUSE','TASK_RESUME','TASK_CANCEL','TASK_GET_HISTORY','SETTINGS_UPDATE'];
const EVENTS=['APP_HEALTH_CHANGED','TASK_STATE_CHANGED','STEP_STARTED','STEP_COMPLETED','VERIFICATION_COMPLETED','RECOVERY_STARTED','APPROVAL_REQUIRED','ERROR_OCCURRED','TASK_FINALIZED'];
const ERROR_CODES=['UI_BACKEND_DISCONNECTED','UI_COMMAND_INVALID','UI_EVENT_SYNC_FAILED','TASK_STATE_CONFLICT','APPROVAL_STATE_INVALID','HEALTH_CHECK_FAILED','SETTINGS_VALIDATION_FAILED','LOCALIZATION_RESOURCE_MISSING','EVIDENCE_ACCESS_DENIED','UPDATE_VERIFICATION_FAILED'];
let task=null,timer=null,history=JSON.parse(localStorage.getItem('lmw-history')||'[]'),fingerprint='';
let health={core:true,model:true,browser:true,memory:true,security:true};
function command(type,payload={}){if(!COMMANDS.includes(type))throw Error('UI_COMMAND_INVALID');return{type,payload}}
function event(type,payload={}){if(!EVENTS.includes(type))throw Error('UI_EVENT_SYNC_FAILED');window.dispatchEvent(new CustomEvent(type,{detail:payload}))}
function save(){localStorage.setItem('lmw-history',JSON.stringify(history))}
function msg(t,c){$('welcome').style.display='none';let d=document.createElement('div');d.className='msg '+c;d.textContent=t;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
function risk(s){return /delete|remove|erase|send|purchase|pay|shutdown|uninstall/i.test(s)}
function allHealthy(){return Object.values(health).every(Boolean)}
function render(){let b=$('badge'),a=$('activity');b.textContent=task?task.status:'READY';a.innerHTML='';if(!task){a.textContent='No active task.';return}task.steps.forEach((x,i)=>{let d=document.createElement('div');d.className='step '+(i<task.i?'done ':'')+(i===task.i?'current':'');d.textContent=(i<task.i?'✓ ':'○ ')+x[0]+' — '+x[1];a.appendChild(d)});$('pause').disabled=task.status!==STATES.EXECUTING;$('resume').disabled=task.status!==STATES.PAUSED;$('cancel').disabled=[STATES.COMPLETED,STATES.CANCELLED,STATES.FAILED].includes(task.status)}
function start(){let s=$('input').value.trim();if(!s)return;if(risk(s)&&!allHealthy()){msg('This action needs a healthy system to run safely. Check Diagnostics before starting a risky task.','system');event('ERROR_OCCURRED',{code:'HEALTH_CHECK_FAILED'});return}command('TASK_CREATE',{instruction:s});task={id:crypto.randomUUID(),instruction:s,status:STATES.TASK_CREATING,i:0,steps:[['Understand instruction','Core'],['Prepare plan','Boss Agent'],[risk(s)?'Await approval':'Execute plan','Security / Workers'],['Perform actions','Workers'],['Verify result','Verification'],['Final report','Core']]};msg(s,'user');msg('Task created. I will show clarification or approval when required.','system');$('input').value='';render();timer=setTimeout(stage,500)}
function stage(){if(!task||[STATES.PAUSED,STATES.CANCELLED].includes(task.status))return;if(task.i===0){task.status=STATES.TASK_PLANNING;task.i=1}else if(task.i===1){task.i=2;if(risk(task.instruction)){task.status=STATES.WAITING_FOR_APPROVAL;fingerprint=btoa(task.instruction+'|'+task.i);$('details').innerHTML='<b>Action:</b> '+esc(task.instruction)+'<br><b>Target:</b> Derived from instruction<br><b>Impact:</b> This may be irreversible; recovery is not guaranteed.';openModal();event('APPROVAL_REQUIRED',{fingerprint});render();return}else task.status=STATES.EXECUTING}else if(task.i<5){task.status=STATES.EXECUTING;task.i++}else{task.status=STATES.VERIFYING;render();return timer=setTimeout(()=>{task.status=STATES.COMPLETED;history.unshift({title:task.instruction,status:task.status,time:new Date().toLocaleString(),summary:'Independently verified result'});save();msg('Completed. Result independently verified.','system');event('VERIFICATION_COMPLETED',{verified:true});event('TASK_FINALIZED',{status:task.status});render()},900)}render();timer=setTimeout(stage,700)}
function esc(s){return s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function openModal(){let m=$('modal');m.classList.add('show');m.dataset.returnFocus=document.activeElement&&document.activeElement.id||'';$('reject').focus()}
function closeModal(){$('modal').classList.remove('show');let id=$('modal').dataset.returnFocus;if(id&&$(id))$(id).focus()}
$('create').onclick=start;$('input').onkeydown=e=>{if(e.ctrlKey&&e.key==='Enter')start()};
$('approve').onclick=()=>{if(!task||task.status!==STATES.WAITING_FOR_APPROVAL)return;if(fingerprint!==btoa(task.instruction+'|'+task.i)){event('ERROR_OCCURRED',{code:'APPROVAL_STATE_INVALID'});closeModal();return}command('TASK_APPROVE',{fingerprint});closeModal();task.status=STATES.EXECUTING;task.i++;render();timer=setTimeout(stage,600)};
$('reject').onclick=()=>{if(!task)return;command('TASK_REJECT');closeModal();task.status=STATES.CANCELLED;history.unshift({title:task.instruction,status:task.status,time:new Date().toLocaleString(),summary:'User rejected approval'});save();render()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('modal').classList.contains('show'))$('reject').click()});
$('pause').onclick=()=>{if(task?.status!==STATES.EXECUTING)return;clearTimeout(timer);command('TASK_PAUSE');task.status=STATES.PAUSED;render()};
$('resume').onclick=()=>{if(task?.status!==STATES.PAUSED)return;command('TASK_RESUME');task.status=STATES.EXECUTING;render();timer=setTimeout(stage,500)};
$('cancel').onclick=()=>{if(!task)return;clearTimeout(timer);command('TASK_CANCEL');closeModal();task.status=STATES.CANCELLED;history.unshift({title:task.instruction,status:task.status,time:new Date().toLocaleString(),summary:'Safely cancelled; no automatic undo promised'});save();render()};
document.querySelectorAll('aside button[data-page]').forEach(b=>b.onclick=()=>{let p=b.dataset.page;document.querySelectorAll('main section').forEach(s=>s.classList.remove('active'));document.querySelectorAll('aside button[data-page]').forEach(x=>x.removeAttribute('aria-current'));$(p).classList.add('active');b.setAttribute('aria-current','page');$('title').textContent=p[0].toUpperCase()+p.slice(1);if(p==='history'){command('TASK_GET_HISTORY');$('historyList').innerHTML=history.length?history.map(x=>'<div class="step"><b>'+esc(x.title)+'</b><br><small>'+x.time+' • '+x.status+' • '+esc(x.summary)+'</small></div>').join(''):'No task history.'}if(p==='diagnostics')renderDiag()});
$('forget').onclick=()=>{history=[];save();$('historyList').textContent='No task history.'};
function renderDiag(){let names={core:'Core (Part 01)',model:'Model / runtime (Part 03)',browser:'Browser worker (Part 05)',memory:'Memory store (Part 08)',security:'Security service (Part 09)'};$('diag').innerHTML=Object.keys(health).map(k=>'<div class="step">'+(health[k]?'✓ ':'✕ ')+names[k]+' — '+(health[k]?'healthy':'unhealthy')+'</div>').join('')}
$('repair').onclick=()=>{Object.keys(health).forEach(k=>health[k]=true);renderDiag();updateHealthUI();alert('Repair check completed: no critical issue found.')};
function updateHealthUI(){event('APP_HEALTH_CHANGED',{healthy:allHealthy()})}
window.addEventListener('APP_HEALTH_CHANGED',e=>{$('health').textContent=e.detail?.healthy===false?'● Critical subsystem unhealthy':'● System healthy'});
$('langSelect').onchange=e=>{$('lang').textContent=e.target.value==='বাংলা'?'বাংলা':'বাংলা / EN'};
$('lang').onclick=()=>{let sel=$('langSelect');sel.selectedIndex=(sel.selectedIndex+1)%sel.options.length;sel.dispatchEvent(new Event('change'));msg('Interface language set to '+sel.value+'. Full translation resources load from the localization layer.','system')};
$('motionReduction').onchange=e=>document.body.classList.toggle('reduce-motion',e.target.checked);
$('textScale').oninput=e=>document.documentElement.style.fontSize=(e.target.value*100)+'%';
[$('motionReduction'),$('textScale'),$('retention'),$('langSelect')].forEach(el=>el.addEventListener('change',()=>command('SETTINGS_UPDATE',{})));
renderDiag();updateHealthUI();render();
